version: '3.8'
services:
  duckdns:
    image: maksimstojkovic/duckdns
    container_name: duckdns
    environment:
      - DUCKDNS_TOKEN=__DUCKDNS_TOKEN__
      - DUCKDNS_DOMAIN=__DOMAIN__
      - DUCKDNS_DELAY=5
    restart: unless-stopped

  letsencrypt:
    image: maksimstojkovic/letsencrypt
    container_name: letsencrypt
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - DUCKDNS_TOKEN=__DUCKDNS_TOKEN__
      - DUCKDNS_DOMAIN=__DOMAIN__
    restart: unless-stopped

  postgres:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes: 
      - postgres:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  tocata-stream-server:
    image: ghcr.io/numeroband/tocata-stream-server
    container_name: tocata-stream-server
    depends_on:
      - postgres
    expose:
      - "3000"
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/postgres'
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - ./letsencrypt:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

volumes:
  postgres:
    driver: local

